// Runs an ONNX model through onnxruntime-web's WebGPU execution provider
// with ONE node excised and replaced by a custom WebGPU program (as
// generated by onnxsim.webgpu_tinygrad_codegen and attached via
// onnxsim/webgpu_kernel_metadata.py) -- the "runtime on top of ort-web"
// piece that module's own docstring described as not built yet.
//
// The excised node's inputs/outputs never round-trip through the CPU: this
// runs two ordinary onnxruntime-web sessions (`pre`, the part of the graph
// upstream of the node; `post`, the part downstream) with
// `preferredOutputLocation: 'gpu-buffer'`, dispatches the custom program via
// webgpu_kernel_dispatcher.mjs's dispatchWebgpuProgram against the SAME
// GPUDevice ort-web's own WebGPU backend uses (retrieved via
// `ort.env.webgpu.device` -- per onnxruntime-web's own env docs, reading
// this *after* the first session is created returns the device the backend
// is actually using), and feeds the result into `post` via
// `ort.Tensor.fromGpuBuffer` -- the same GPU-buffer interop pattern
// onnxruntime-web itself uses for chaining sessions.
//
// `pre`/`post` are produced by onnxsim.webgpu_custom_kernel_runtime.split_around_node
// -- see that module's own docstring for why the node must be *physically*
// removed from both graphs rather than left in place and expected to fail
// gracefully (onnxruntime-web's WebGPU partitioner commits a node to WebGPU
// by op type alone, so an unsupported *variant* of a supported op is only
// caught once its kernel actually runs, failing the whole session).
//
// ## Scope (v1)
//
// `preModelBytes` is required: this only covers a node whose inputs are at
// least partly produced by another node (the common case -- a Conv/Resize
// buried in a real network, not the very first op). `split_around_node`
// itself also supports a node that consumes only the original graph's own
// top-level inputs (`pre` is `None` there) -- that case isn't wired up on
// this JS side yet; a caller in that situation would need to pass all of
// the node's inputs via `extraInputs` and skip `preSession`/`feeds`
// entirely, which this module does not do for you.
//
// Also out of scope, matching onnxsim/webgpu_kernel_metadata.py's own
// schema: a `dispatch` size that depends on a dynamic input shape (this
// only ever targets a node whose shapes -- and therefore whose generated
// dispatch size -- are fixed at kernel-generation time), and more than one
// excised node per model (call this once; chaining several is up to the
// caller).
//
// See scripts/convertmodel/test/webgpu_custom_kernel_runtime.test.mjs for
// the real-GPU, real-onnxruntime-web proof this actually works end to end.

import { dispatchWebgpuProgram, createStorageBuffer } from "./webgpu_kernel_dispatcher.mjs";

const DTYPE_BYTES = { float32: 4, float16: 2, int32: 4, uint32: 4, uint8: 1, bool: 1 };

/**
 * @param {object} args
 * @param {object} args.ort - an already-loaded onnxruntime-web module
 *        (`import(".../ort.all.bundle.min.mjs")`), so this module stays
 *        agnostic about how/where the caller loads it from.
 * @param {Uint8Array} args.preModelBytes - the `pre` sub-model's bytes
 *        (see split_around_node.pre).
 * @param {Uint8Array} args.postModelBytes - the `post` sub-model's bytes
 *        (see split_around_node.post).
 * @param {object} args.spec - the excised node's WebgpuKernelSpec, as JSON
 *        (same shape onnx_node_metadata.mjs's readWebgpuKernelSpecs returns).
 * @param {Object<string, InstanceType<object>>} args.feeds - CPU-side
 *        `ort.Tensor`s, keyed by tensor name: every input `pre` needs, plus
 *        any input `post` needs directly (a "side input" that bypasses both
 *        `pre` and the excised node -- see split_model's own docstring, via
 *        onnxsim/webgpu_custom_kernel_runtime.py, for why that can happen).
 * @param {Object<string, Float32Array|number[]>} [args.extraInputs] - node
 *        inputs neither `pre`'s outputs nor `feeds` supply -- typically an
 *        initializer the excised node itself needed (e.g. a Conv weight),
 *        which split_around_node deliberately leaves for the caller to
 *        source from the *original* (unsplit) model, since a program's
 *        bindings only name tensors, not carry their data. Keyed by tensor
 *        name, values plain data this function uploads itself (as a
 *        storage buffer on the *same* device the two sessions use --
 *        building the buffer here, after that device is known, rather than
 *        asking the caller to create it beforehand, sidesteps a real
 *        failure mode: a `GPUDevice` obtained any other way (e.g. the
 *        caller's own `navigator.gpu.requestAdapter()`) is not guaranteed
 *        to be the one onnxruntime-web's WebGPU backend actually ends up
 *        using, and a buffer from the wrong device fails with "is
 *        associated with [Device], and cannot be used with [Device]" the
 *        instant it's bound anywhere).
 * @param {Array<{name: string, dims: number[], dataType: string}>} args.nodeOutputs
 *        - the excised node's own output tensors' shape/dtype (needed to
 *        size the buffers this allocates for the dispatch to write into,
 *        and to wrap them as `ort.Tensor.fromGpuBuffer` for `post`).
 * @param {string[]} args.finalOutputNames - names to read back from `post`.
 * @param {object} [args.sessionOptions]
 * @param {boolean} [args.profile] - time the excised node's own program on
 *        the GPU via `dispatchWebgpuProgram`'s own `profile` option -- see
 *        that function's own docstring for the two timestamp-query
 *        mechanisms it picks between and why it's normally available here
 *        for free (onnxruntime-web's WebGPU backend requests one of them
 *        unconditionally when the adapter supports it, and this runtime
 *        shares *that* device -- verified this is usually the Chromium one,
 *        not the standard one, which is exactly why `dispatchWebgpuProgram`
 *        supports both rather than only the standard feature). Adds
 *        negligible overhead when `false` (the default) -- no query set is
 *        created at all.
 * @returns {Promise<{outputs: Object<string, InstanceType<object>>, profiling: Array<{index: number, entryPoint: string, durationNs: number}> | null}>}
 *        `outputs` are `post`'s results for `finalOutputNames`, as ordinary
 *        onnxruntime-web `ort.Tensor`s (CPU-resident by default -- pass
 *        `postSessionOptions` overrides via `sessionOptions` if a caller
 *        wants to keep chaining on GPU). `profiling` is `null` unless
 *        `profile: true` was passed *and* the shared device supports
 *        `"timestamp-query"` (a caller who needs to tell "didn't ask" apart
 *        from "device can't do it" can check
 *        `webgpu_kernel_dispatcher.mjs`'s own `supportsWebgpuProfiling(await
 *        ort.env.webgpu.device)`) -- otherwise one entry per program step,
 *        in step order, matching `dispatchWebgpuProgram`'s own return shape.
 */
export async function runOnnxModelWithCustomKernel({
  ort,
  preModelBytes,
  postModelBytes,
  spec,
  feeds,
  extraInputs = {},
  nodeOutputs,
  finalOutputNames,
  sessionOptions = { executionProviders: ["webgpu"], graphOptimizationLevel: "disabled" },
  profile = false,
}) {
  // preferredOutputLocation is a *session-creation* option (SessionOptions),
  // not a per-run one (RunOptions) -- passing it to run() instead silently
  // does nothing, and the output tensor's own .gpuBuffer getter then throws
  // "The data is not stored as a WebGPU buffer."
  const preSession = await ort.InferenceSession.create(preModelBytes, {
    ...sessionOptions,
    preferredOutputLocation: "gpu-buffer",
  });
  const postSession = await ort.InferenceSession.create(postModelBytes, sessionOptions);

  // Per onnxruntime-web's own env docs: reading env.webgpu.device *after*
  // the first WebGPU session exists returns the GPUDevice the backend is
  // actually using -- the device our own dispatch must share to touch the
  // same buffers.
  const device = await ort.env.webgpu.device;

  const preResults = await preSession.run(feeds);

  const buffersByTensor = new Map();
  for (const [name, data] of Object.entries(extraInputs)) {
    buffersByTensor.set(name, createStorageBuffer(device, Float32Array.from(data)));
  }
  for (const [name, tensor] of Object.entries(preResults)) {
    buffersByTensor.set(name, tensor.gpuBuffer);
  }

  for (const { name, dims, dataType } of nodeOutputs) {
    const elementCount = dims.reduce((a, b) => a * b, 1);
    const byteLength = elementCount * (DTYPE_BYTES[dataType] ?? 4);
    buffersByTensor.set(
      name,
      device.createBuffer({
        size: byteLength,
        // STORAGE so our own WGSL can write it; COPY_SRC/COPY_DST so
        // onnxruntime-web's WebGPU backend can freely copy/transition it
        // once wrapped as one of its own input tensors below.
        usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST,
      }),
    );
  }

  const { timings } = await dispatchWebgpuProgram(device, spec, buffersByTensor, { profile });

  const available = { ...feeds };
  for (const { name, dims, dataType } of nodeOutputs) {
    available[name] = ort.Tensor.fromGpuBuffer(buffersByTensor.get(name), { dataType, dims });
  }
  const postFeeds = {};
  for (const name of postSession.inputNames) {
    if (available[name] !== undefined) postFeeds[name] = available[name];
  }

  const results = await postSession.run(postFeeds);
  const outputs = {};
  for (const name of finalOutputNames) outputs[name] = results[name];

  await preSession.release?.();
  await postSession.release?.();
  return { outputs, profiling: timings };
}
