#!/usr/bin/env python3
"""Assemble a Windows onnxsim wheel from a cross-compiled .pyd.

setup.py cannot drive the final packaging when cross-compiling (it assumes the
host's extension suffix and build layout), so this script builds a correctly
tagged wheel directly from the pure-python sources plus the pre-built extension.

It mirrors the metadata that ``setup.py`` / ``pyproject.toml`` would produce:
the version string (with the same ``.devN`` suffix logic), the runtime
dependencies, and the ``onnxsim`` console-script entry point.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


def compute_version(repo_root: Path) -> str:
    """Reproduce the version string used by setup.py."""
    release = os.getenv("ONNXSIM_RELEASE")
    if release:
        return release.lstrip("v")

    version = (repo_root / "VERSION").read_text().strip()
    dev_count = None
    try:
        dev_count = subprocess.check_output(
            ["git", "rev-list", "--count", f"v{version}..HEAD"],
            cwd=repo_root,
        ).decode("ascii").strip()
    except (OSError, subprocess.CalledProcessError):
        dev_count = None
    if dev_count and dev_count != "0":
        version += f".dev{dev_count}"
    return version


def write_version_py(pkg_dir: Path, version: str, repo_root: Path) -> None:
    try:
        git_version = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=repo_root
        ).decode("ascii").strip()
    except (OSError, subprocess.CalledProcessError):
        git_version = None
    (pkg_dir / "version.py").write_text(
        "# This file is generated by assemble_wheel.py. DO NOT EDIT!\n\n"
        f"version = '{version}'\n"
        f"git_version = '{git_version}'\n"
        "dev_count = None\n"
    )


METADATA = """\
Metadata-Version: 2.1
Name: onnxsim
Version: {version}
Summary: Simplify your ONNX model
Home-page: https://github.com/onnxsim/onnxsim
Author: ONNX Simplifier Authors
Author-email: daquexian566@gmail.com
License: MIT AND (Apache-2.0 OR BSD-2-Clause)
Keywords: deep-learning,ONNX
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Topic :: Scientific/Engineering
Classifier: Topic :: Software Development
Requires-Python: >=3.11
Requires-Dist: onnx
Provides-Extra: onnxruntime
Requires-Dist: onnxruntime >=1.6.0 ; extra == 'onnxruntime'
Provides-Extra: rich
Requires-Dist: rich !=12.1.0 ; extra == 'rich'
Description-Content-Type: text/markdown

Simplify your ONNX model. See https://github.com/onnxsim/onnxsim for details.
"""

WHEEL = """\
Wheel-Version: 1.0
Generator: onnxsim-cross-build
Root-Is-Purelib: false
Tag: {tag}
"""

ENTRY_POINTS = """\
[console_scripts]
onnxsim = onnxsim:main
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True, type=Path)
    ap.add_argument("--pyd", required=True, type=Path)
    ap.add_argument("--pyver", required=True, help="e.g. 3.12")
    ap.add_argument("--abi3", default="0")
    ap.add_argument("--outdir", required=True, type=Path)
    args = ap.parse_args()

    repo_root: Path = args.repo_root.resolve()
    version = compute_version(repo_root)
    nodot = args.pyver.replace(".", "")
    abi3 = args.abi3 == "1"
    tag = f"cp{nodot}-abi3-win_amd64" if abi3 else f"cp{nodot}-cp{nodot}-win_amd64"

    stage = args.outdir / f".stage-{tag}"
    if stage.exists():
        shutil.rmtree(stage)
    pkg_dir = stage / "onnxsim"
    dist_info = stage / f"onnxsim-{version}.dist-info"
    pkg_dir.mkdir(parents=True)
    dist_info.mkdir(parents=True)

    # pure-python sources
    src_pkg = repo_root / "onnxsim"
    for py in sorted(src_pkg.glob("*.py")):
        shutil.copy2(py, pkg_dir / py.name)
    write_version_py(pkg_dir, version, repo_root)

    # the cross-compiled extension (Windows loads it as <name>.pyd)
    shutil.copy2(args.pyd, pkg_dir / "onnxsim_cpp2py_export.pyd")

    (dist_info / "METADATA").write_text(METADATA.format(version=version))
    (dist_info / "WHEEL").write_text(WHEEL.format(tag=tag))
    (dist_info / "entry_points.txt").write_text(ENTRY_POINTS)
    (dist_info / "top_level.txt").write_text("onnxsim\n")

    args.outdir.mkdir(parents=True, exist_ok=True)
    subprocess.check_call(
        [sys.executable, "-m", "wheel", "pack", str(stage), "--dest-dir", str(args.outdir)]
    )
    shutil.rmtree(stage)
    print(f"packed onnxsim-{version} [{tag}] into {args.outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
