import sysconfig
import setuptools
import setuptools.command.build_py
import setuptools.command.develop
import setuptools.command.build_ext

from collections import namedtuple
from contextlib import contextmanager
import os
import shlex
import subprocess
import shutil
import sys
from textwrap import dedent
import multiprocessing
import re


TOP_DIR = os.path.realpath(os.path.dirname(__file__))
SRC_DIR = os.path.join(TOP_DIR, 'onnxsim')
CMAKE_BUILD_DIR = os.path.join(TOP_DIR, '.setuptools-cmake-build')

WINDOWS = (os.name == 'nt')
MACOS = sys.platform.startswith("darwin")

CMAKE = shutil.which('cmake')

USE_MSVC_STATIC_RUNTIME = bool(os.getenv('USE_MSVC_STATIC_RUNTIME', '0') == '1')
ONNX_ML = not bool(os.getenv('ONNX_ML') == '0')
ONNX_VERIFY_PROTO3 = bool(os.getenv('ONNX_VERIFY_PROTO3') == '1')
ONNX_NAMESPACE = os.getenv('ONNX_NAMESPACE', 'onnx')
ONNX_BUILD_TESTS = bool(os.getenv('ONNX_BUILD_TESTS') == '1')
ONNX_OPT_USE_SYSTEM_PROTOBUF = bool(os.getenv('ONNX_OPT_USE_SYSTEM_PROTOBUF', '0') == '1')
IS_FREE_THREADED = sysconfig.get_config_var("Py_GIL_DISABLED")

DEBUG = bool(os.getenv('DEBUG'))
COVERAGE = bool(os.getenv('COVERAGE'))
VERSION_FILE = os.path.join(TOP_DIR, 'VERSION')

# Opt-in only -- see docs/wasm_pyodide.md. When building under `pyodide build`
# (pywasmcross-wrapped compilers targeting wasm32-emscripten), CMake's own
# MODULE/SHARED library support is unavailable (Emscripten's CMake toolchain
# file hardcodes TARGET_SUPPORTS_SHARED_LIBS=FALSE), so the
# onnxsim_cpp2py_export target CMake produces is a static ar archive, not a
# loadable Pyodide side module -- byte-identical to the dead end
# build_wasm_pyodide.sh's manual em++ relink step already works around.
# This flag makes build_ext perform that exact same manual relink, in place,
# before the artifact is copied into the wheel. It does nothing (and this
# whole code path is not even imported/evaluated beyond this flag check)
# unless explicitly set -- a normal `pip install .` / native wheel build is
# completely unaffected. Deliberately an explicit env var rather than
# auto-detection, so this never silently changes native-build behavior.
ONNXSIM_WASM_SIDE_MODULE_RELINK = bool(
    os.getenv('ONNXSIM_WASM_SIDE_MODULE_RELINK') == '1')

try:
    version = subprocess.check_output(['git', 'describe', '--tags', '--abbrev=0'],
                                      cwd=TOP_DIR).decode('ascii').strip()
    if version[0] == 'v':
        version = version[1:]
    with open(VERSION_FILE, "w") as f:
        f.write(version + "\n")
except (OSError, subprocess.CalledProcessError):
    with open(VERSION_FILE) as ver_file:
        version = ver_file.read().strip()

try:
    git_version = subprocess.check_output(['git', 'rev-parse', 'HEAD'],
                                          cwd=TOP_DIR).decode('ascii').strip()
except (OSError, subprocess.CalledProcessError):
    git_version = None

try:
    dev_count = subprocess.check_output(['git', 'rev-list', '--count', f"v{version}..HEAD"]).decode('ascii').strip()
except (OSError, subprocess.CalledProcessError):
    dev_count = None

if os.getenv('ONNXSIM_RELEASE') is not None:
    version = os.getenv('ONNXSIM_RELEASE')
    git_version = None
    dev_count = None

VersionInfo = namedtuple('VersionInfo', ['version', 'git_version', 'dev_count'])(
    version=version,
    git_version=git_version,
    dev_count=dev_count,
)

assert CMAKE, 'Could not find "cmake" executable!'

@contextmanager
def cd(path):
    if not os.path.isabs(path):
        raise RuntimeError('Can only cd to absolute path, got: {}'.format(path))
    orig_path = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(orig_path)


class ONNXCommand(setuptools.Command):
    user_options = []

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass


class create_version(ONNXCommand):
    def run(self):
        with open(os.path.join(SRC_DIR, 'version.py'), 'w') as f:
            f.write(dedent('''\
            # This file is generated by setup.py. DO NOT EDIT!

            version = '{version}'
            git_version = '{git_version}'
            dev_count = {dev_count}
            '''.format(**dict(VersionInfo._asdict()))))


class cmake_build(setuptools.Command):
    """
    Compiles everything when `python setupmnm.py build` is run using cmake.

    Custom args can be passed to cmake by specifying the `CMAKE_ARGS`
    environment variable.

    The number of CPUs used by `make` can be specified by passing `-j<ncpus>`
    to `setup.py build`.  By default all CPUs are used.
    """
    user_options = [
        (str('jobs='), str('j'), str('Specifies the number of jobs to use with make'))
    ]

    built = False

    def initialize_options(self):
        self.jobs = None

    def finalize_options(self):
        self.set_undefined_options('build', ('parallel', 'jobs'))
        if self.jobs is None and os.getenv("MAX_JOBS") is not None:
            self.jobs = os.getenv("MAX_JOBS")
        self.jobs = multiprocessing.cpu_count() if self.jobs is None else int(self.jobs)

    def run(self):
        if cmake_build.built:
            return
        cmake_build.built = True
        if not os.path.exists(CMAKE_BUILD_DIR):
            os.makedirs(CMAKE_BUILD_DIR)

        with cd(CMAKE_BUILD_DIR):
            build_type = 'RelWithDebInfo'
            if WINDOWS:
                build_type = 'Release'
            # configure
            # onnx's own CMakeLists.txt calls the VERSIONED find_package(Python3
            # ...), needing Python3_EXECUTABLE/Python3_INCLUDE_DIR(S); nanobind's
            # own CMake config separately reads the plural, unversioned
            # Python_INCLUDE_DIRS. A normal native build never needed these --
            # CMake's automatic Python3 discovery just finds the host
            # interpreter -- but pyodide build's cross-compilation environment
            # doesn't seed those hints on its own, so `find_package(Python3
            # ...)` fails outright there ("Could NOT find Python3 (missing:
            # Python3_INCLUDE_DIRS Development.Module)") unless they're passed
            # explicitly, same as build_wasm_pyodide.sh already does for its own
            # (separate, non-setup.py) CMake invocation. Passing them here too,
            # to the exact same values as the Python_* hints below, is a no-op
            # for every existing native build (same interpreter/headers CMake
            # would already have auto-discovered) and is what lets
            # ONNXSIM_WASM_SIDE_MODULE_RELINK's `pyodide build` path configure
            # at all. See docs/wasm_pyodide.md.
            python_include = sysconfig.get_path('include')
            cmake_args = [
                CMAKE,
                '-DPython_INCLUDE_DIR={}'.format(python_include),
                '-DPython_INCLUDE_DIRS={}'.format(python_include),
                '-DPython_EXECUTABLE={}'.format(sys.executable),
                '-DPython3_INCLUDE_DIR={}'.format(python_include),
                '-DPython3_INCLUDE_DIRS={}'.format(python_include),
                '-DPython3_EXECUTABLE={}'.format(sys.executable),
                '-DONNX_BUILD_PYTHON=ON',
                "-DONNX_INSTALL=OFF",
                '-DONNXSIM_PYTHON=ON',
                '-DONNXSIM_BUILTIN_ORT=OFF',
                '-DONNX_USE_LITE_PROTO=ON',
                '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON',
                '-DONNX_NAMESPACE={}'.format(ONNX_NAMESPACE),
                '-DONNX_OPT_USE_SYSTEM_PROTOBUF={}'.format(
                    'ON' if ONNX_OPT_USE_SYSTEM_PROTOBUF else 'OFF'),
            ]
            if IS_FREE_THREADED:
                cmake_args.append('-DPython3_FIND_ABI=ANY;ANY;ANY;ANY')
            if ONNXSIM_WASM_SIDE_MODULE_RELINK:
                # nanobind 3.0.0's nb_backend.h/nb_types.h/ndarray.h use
                # stderr/fprintf without including <cstdio> -- works by
                # accident on glibc hosts (pulled in transitively through
                # some other header) and fails outright under Emscripten's
                # libc++, which doesn't ("error: use of undeclared
                # identifier 'stderr'"). Real upstream nanobind bug, not
                # onnxsim-specific -- build_wasm_pyodide.sh already works
                # around it the same way for its own CMake invocation. See
                # docs/wasm_pyodide.md.
                cmake_args.append('-DCMAKE_CXX_FLAGS=-include cstdio')
                # Without an override, onnx's own CMakeLists.txt (see its
                # relative_protobuf_generate_cpp()) defaults
                # ONNX_PROTOC_EXECUTABLE to the in-tree, JUST-CROSS-BUILT
                # `protoc` target -- under wasm32-emscripten, a Node-
                # launched .js wrapper (e.g. protoc.js-31.1.0), invoked as
                # a PLAIN `COMMAND "${ONNX_PROTOC_EXECUTABLE}" ...` with no
                # CMAKE_CROSSCOMPILING_EMULATOR/node wrapping at all.
                # Confirmed directly (both in onnx/CMakeLists.txt and by
                # testing CMAKE_CROSSCOMPILING_EMULATOR, which has zero
                # effect here since nothing reads it for this custom
                # command): this only works when the file itself is
                # directly executable, which it apparently isn't inside
                # `pyodide build`'s isolated build env ("Permission
                # denied" trying to exec protoc.js-31.1.0). Same
                # requirement as obstacle 1 in docs/wasm_pyodide.md:
                # build_wasm_pyodide.sh sidesteps this identical problem
                # entirely by pointing ONNX_CUSTOM_PROTOC_EXECUTABLE at a
                # HOST protoc binary instead (a normal native executable,
                # no cross-exec concerns) -- do the same here. The CI job
                # setting ONNXSIM_WASM_SIDE_MODULE_RELINK=1 is expected to
                # have already installed a matching host protoc (same
                # version as onnxsim's vendored protobuf) on PATH, exactly
                # as pyodide-wasm.yml's own job already does.
                protoc = shutil.which('protoc')
                if protoc:
                    cmake_args.append(
                        '-DONNX_CUSTOM_PROTOC_EXECUTABLE={}'.format(protoc))
            if COVERAGE:
                cmake_args.append('-DONNX_COVERAGE=ON')
                # Instrument onnxsim's own C++ (onnxsim.cpp, cpp2py_export.cc,
                # ...) too, so a pytest run reports coverage for the code that
                # actually runs behind the Python extension, not just vendored
                # ONNX. gcovr collects the resulting .gcda from the build dir.
                cmake_args.append('-DONNXSIM_COVERAGE=ON')
            if COVERAGE or DEBUG:
                # in order to get accurate coverage information, the
                # build needs to turn off optimizations
                build_type = 'Debug'
            cmake_args.append('-DCMAKE_BUILD_TYPE=%s' % build_type)
            if WINDOWS:
                cmake_args.extend([
                    # we need to link with libpython on windows, so
                    # passing python version to window in order to
                    # find python in cmake
                    '-DPY_VERSION={}'.format('{0}.{1}'.format(* \
                                                              sys.version_info[:2])),
                ])
                if USE_MSVC_STATIC_RUNTIME:
                    cmake_args.append('-DONNX_USE_MSVC_STATIC_RUNTIME=ON')
            if MACOS:
                # Cross-compile support for macOS - respect ARCHFLAGS if set
                archs = re.findall(r"-arch (\S+)", os.environ.get("ARCHFLAGS", ""))
                if archs:
                    cmake_args += ["-DCMAKE_OSX_ARCHITECTURES={}".format(";".join(archs))]
            if ONNX_ML:
                cmake_args.append('-DONNX_ML=1')
            if ONNX_VERIFY_PROTO3:
                cmake_args.append('-DONNX_VERIFY_PROTO3=1')
            if ONNX_BUILD_TESTS:
                cmake_args.append('-DONNX_BUILD_TESTS=ON')
            if 'CMAKE_ARGS' in os.environ:
                extra_cmake_args = shlex.split(os.environ['CMAKE_ARGS'])
                # prevent crossfire with downstream scripts
                del os.environ['CMAKE_ARGS']
                print('Extra cmake args: {}'.format(extra_cmake_args))
                cmake_args.extend(extra_cmake_args)
            cmake_args.append(TOP_DIR)
            print(f"Run command {cmake_args}")
            subprocess.check_call(cmake_args)

            build_args = [CMAKE, '--build', os.curdir, '--target', 'onnxsim_cpp2py_export']
            print(f"Run command {build_args}")
            subprocess.check_call(build_args)


class build_py(setuptools.command.build_py.build_py):
    def run(self):
        self.run_command('create_version')
        return setuptools.command.build_py.build_py.run(self)


class develop(setuptools.command.develop.develop):
    def run(self):
        self.run_command('build_py')
        setuptools.command.develop.develop.run(self)


def _relink_wasm_side_module(build_dir, so_path):
    """Re-link `so_path` (a CMake-produced static ar archive containing only
    onnxsim_cpp2py_export's own object file, under Emscripten's CMake
    toolchain -- see ONNXSIM_WASM_SIDE_MODULE_RELINK above) into a genuine
    Pyodide side module, in place.

    Exact same approach as build_wasm_pyodide.sh's manual link step: reuses
    the object file and every dependency archive (abseil/protobuf/onnx/
    onnx-optimizer/onnxsim/nanobind) CMake already built under `build_dir`,
    discovering both at run time rather than hand-maintaining a list. See
    docs/wasm_pyodide.md for why this manual step is necessary at all.
    """
    em_plus_plus = shutil.which('em++')
    if not em_plus_plus:
        raise RuntimeError(
            'ONNXSIM_WASM_SIDE_MODULE_RELINK=1 but no em++ on PATH -- '
            'activate the emsdk (or run under pyodide build, which puts a '
            'pywasmcross-wrapped em++ on PATH) before building.')

    module_name = 'onnxsim_cpp2py_export'
    obj = None
    for root, _dirs, files in os.walk(
            os.path.join(build_dir, 'CMakeFiles', f'{module_name}.dir')):
        for f in files:
            if f == 'cpp2py_export.cc.o':
                obj = os.path.join(root, f)
                break
        if obj:
            break
    if not obj:
        raise RuntimeError(
            f'ONNXSIM_WASM_SIDE_MODULE_RELINK=1: could not find '
            f'cpp2py_export.cc.o under {build_dir}/CMakeFiles/'
            f'{module_name}.dir (did the CMake build actually run?)')

    archives = []
    for root, _dirs, files in os.walk(build_dir):
        for f in files:
            if f.endswith('.a'):
                archives.append(os.path.join(root, f))
    archives.sort()
    if not archives:
        raise RuntimeError(
            f'ONNXSIM_WASM_SIDE_MODULE_RELINK=1: no .a archives found under '
            f'{build_dir} -- expected dependency archives '
            f'(abseil/protobuf/onnx/onnx-optimizer/onnxsim/nanobind) to '
            f'already be built at this point.')

    # Discover the real entry symbol (PyInit_<module name>, per CPython's
    # extension-module ABI) from the object file via llvm-nm rather than
    # assuming it matches module_name, so a future module rename doesn't
    # silently produce a link missing its only real entry point.
    entry_symbol = None
    llvm_nm = shutil.which('llvm-nm')
    if llvm_nm:
        out = subprocess.run([llvm_nm, obj], capture_output=True, text=True)
        for line in out.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[1] == 'T' and parts[2].startswith('PyInit_'):
                entry_symbol = parts[2]
                break
    if not entry_symbol:
        entry_symbol = f'PyInit_{module_name}'

    # -sEXPORTED_FUNCTIONS is required: without an explicit root symbol, the
    # linker's dead-code elimination strips the module down to a couple KB,
    # since nothing else in this standalone link references the nanobind
    # entry point (there's no main()/other symbol pulling it in, unlike
    # inside Pyodide's real loader).
    cmd = [
        em_plus_plus, '-O2', '-sSIDE_MODULE=2',
        f'-sEXPORTED_FUNCTIONS=_{entry_symbol}',
        '-o', so_path, obj,
    ] + archives
    print(f'ONNXSIM_WASM_SIDE_MODULE_RELINK=1: relinking wasm side module: '
          f'{" ".join(cmd[:6])} ... (+{len(archives)} archives)')
    subprocess.check_call(cmd)


class build_ext(setuptools.command.build_ext.build_ext):
    def run(self):
        self.run_command('cmake_build')
        setuptools.command.build_ext.build_ext.run(self)

    def build_extensions(self):
        for ext in self.extensions:
            fullname = self.get_ext_fullname(ext.name)
            filename = os.path.basename(self.get_ext_filename(fullname))

            lib_path = CMAKE_BUILD_DIR
            if os.name == 'nt':
                debug_lib_dir = os.path.join(lib_path, "Debug")
                release_lib_dir = os.path.join(lib_path, "Release")
                if os.path.exists(debug_lib_dir):
                    lib_path = debug_lib_dir
                elif os.path.exists(release_lib_dir):
                    lib_path = release_lib_dir
            src = os.path.join(lib_path, filename)
            if ONNXSIM_WASM_SIDE_MODULE_RELINK:
                _relink_wasm_side_module(lib_path, src)
            dst_dir = os.path.join(os.path.realpath(
                self.build_lib), "onnxsim")
            dst = os.path.join(dst_dir, filename)
            os.makedirs(dst_dir, exist_ok=True)
            self.copy_file(src, dst)


cmdclass = {
    'create_version': create_version,
    'cmake_build': cmake_build,
    'build_ext': build_ext,
    'build_py': build_py,
    'develop': develop,
}

py_limited_api = sys.version_info[0] >= 3 and sys.version_info[1] >= 12 and \
    not IS_FREE_THREADED
if py_limited_api:
    setup_opts = {
        'bdist_wheel': {
            'py_limited_api': 'cp312'
        },
    }
else:
    setup_opts = {}

ext_modules = [
    setuptools.Extension(
        name=str('onnxsim.onnxsim_cpp2py_export'),
        sources=[],
        py_limited_api=py_limited_api)
]

packages = setuptools.find_packages()
# onnxsim/bin and onnxsim/capi hold C++ build inputs, not importable Python.
# MANIFEST.in's `recursive-include onnxsim ...` sweeps their sources into the
# sdist, and because they are identifier-named subdirectories of the onnxsim
# package, setuptools both warns ("Package 'onnxsim.bin' is absent from the
# `packages` configuration") and ships the raw .cpp/.h inside every wheel.
# Declare them as packages to silence the warning, then exclude their contents
# (below) so the built wheel carries no stray C++ sources -- they stay in the
# sdist for source builds.
packages += ['onnxsim.bin', 'onnxsim.capi']

version_str = VersionInfo.version

if VersionInfo.dev_count is not None:
    version_str += f".dev{VersionInfo.dev_count}"

# Disabling local version for public release
# if VersionInfo.git_version is not None:
#     version_str += f"+{VersionInfo.git_version}"

setuptools.setup(
    version=version_str,
    ext_modules=ext_modules,
    cmdclass=cmdclass,
    packages=packages,
    include_package_data=True,
    exclude_package_data={'onnxsim.bin': ['*'], 'onnxsim.capi': ['*']},
    options=setup_opts,
)
