"""Tests for ``onnxsim.apply_quip_sharp_cpp`` -- the C++-backed port of
``onnxsim.apply_quip_sharp`` (QuIP#, see ``onnxsim/passes/quip_sharp.h``).
Like every *_cpp port whose scheme depends on a random rotation
(``kmeans_quantization.h``, ``aqlm.h``, ``quarot.h``), this port's own U/V
orthogonal matrices are generated by a genuinely different (though
equally Haar-uniform) construction than quip_sharp.py's own -- see
passes/quip_sharp.h's own "ACCEPTED, PERMANENT DIVERGENCE" note. So these
tests check structural/algebraic properties (the incoherence-processing
rotation making group-wise lattice quantization robust to a concentrated
outlier direction, the fold producing a same-shape float32 replacement
weight with no new graph nodes), never a tight bit-for-bit or numeric
cross-check of the rotation itself against the pure-Python port. The E8
lattice decoding logic itself (``_closest_point_e8``) has no such
divergence -- it is transcribed directly -- so one test below reuses
quip_sharp.py's own reference implementation of it to build a fair
"unrotated" baseline for comparison, without needing to reproduce this
port's own C++ RNG.
"""

import numpy as np
import onnx
import onnx.numpy_helper
import pytest
from onnx import parser

import onnxsim
from onnxsim.quip_sharp import _closest_point_e8

ort = pytest.importorskip("onnxruntime")

_GROUP_SIZE = 8


def _model(body, initializer=(), opset=13, ir_version=8):
    model = parser.parse_model(
        f"""
        <
          ir_version: {ir_version},
          opset_import: ["": {opset}]
        >
        {body}
        """
    )
    model.graph.initializer.extend(initializer)
    return model


def _f32(array, name):
    return onnx.numpy_helper.from_array(array.astype(np.float32), name)


def _matmul_model(w, K, N, batch="batch"):
    return _model(
        f"""
        g (float[{batch},{K}] X) => (float[{batch},{N}] Y)
        {{
          Y = MatMul(X, W)
        }}
        """,
        [_f32(w, "W")],
    )


def _run(model, feeds):
    sess = ort.InferenceSession(
        model.SerializeToString(), providers=["CPUExecutionProvider"]
    )
    return sess.run(None, feeds)


def _rel_l2(a, b):
    a = np.asarray(a, dtype=np.float64).ravel()
    b = np.asarray(b, dtype=np.float64).ravel()
    return np.linalg.norm(a - b) / max(np.linalg.norm(a), 1e-9)


def _current_weight(model, weight_input_index=1):
    # The C++ pass (like every other *_cpp weight-only port here) rewires
    # the matched node's weight input to a freshly created initializer,
    # leaving the original one dangling unused in the graph.
    node = next(n for n in model.graph.node if n.op_type in ("MatMul", "Gemm"))
    w_name = node.input[weight_input_index]
    w_init = next(t for t in model.graph.initializer if t.name == w_name)
    return onnx.numpy_helper.to_array(w_init)


def _naive_group_quant_nk(w_nk_f64, epsilon=1e-8):
    # The SAME per-8-element-group RMS-scale + E8-lattice-decode round
    # trip quip_sharp.py's own apply_quip_sharp (and this port) apply
    # AFTER incoherence-processing rotation, applied here directly to the
    # UNROTATED weight -- a fair "no incoherence processing" baseline for
    # comparison, built from quip_sharp.py's own reference
    # _closest_point_e8 so this baseline is independently correct.
    n_, k_ = w_nk_f64.shape
    num_blocks = k_ // _GROUP_SIZE
    groups = w_nk_f64.reshape(n_ * num_blocks, _GROUP_SIZE)
    scale = np.sqrt(np.mean(groups**2, axis=1)) + epsilon
    native = groups / scale[:, np.newaxis]
    lattice = _closest_point_e8(native)
    codes = np.clip(np.round(lattice * 2.0), -7, 7)
    recon = (codes / 2.0 * scale[:, np.newaxis]).reshape(n_, k_)
    return recon


def test_cpp_replaces_weight_with_same_shape_float():
    rng = np.random.default_rng(0)
    K, N = _GROUP_SIZE * 4, 6
    w = rng.standard_normal((K, N)).astype(np.float32) * 0.5
    model = _matmul_model(w, K, N)

    q = onnxsim.apply_quip_sharp_cpp(model)
    onnx.checker.check_model(q)
    new_w = _current_weight(q)
    assert new_w.shape == w.shape
    assert new_w.dtype == np.float32
    assert not np.array_equal(new_w, w)
    # No new graph nodes -- the whole rotate/quantize/rotate-back sandwich
    # is folded into a single replacement initializer (unlike
    # quip_sharp.py's own MatMul(X, U) -> ... -> MatMul(_, V) rewrite).
    assert [n.op_type for n in q.graph.node] == [n.op_type for n in model.graph.node]
    assert any(t.name == "W" for t in q.graph.initializer)


def test_cpp_incoherence_processing_beats_naive_group_quant_with_outlier_channel():
    # QuIP#'s whole point: a single reduction-dimension index whose
    # magnitude is systematically much larger than the rest (a classic
    # weight/activation "outlier channel") always lands in the SAME
    # 8-element group for every output channel when quantized directly
    # (unrotated) -- that group's shared RMS-based scale is then dominated
    # by the one huge coordinate, washing out its other 7 (small-magnitude)
    # members to near zero. A random orthogonal rotation spreads that one
    # outlier direction's magnitude across every coordinate instead
    # (concentration of measure), so no single post-rotation group is
    # nearly all-outlier -- this is the entire reason incoherence
    # processing helps, independent of which Haar-uniform construction
    # produces U/V. Compared here at the level of the actual linear map
    # (MatMul output), not the raw weight values, so this port's own RNG
    # divergence from quip_sharp.py cannot affect the comparison's
    # validity.
    rng = np.random.default_rng(11)
    K, N = _GROUP_SIZE * 8, 8
    w_nk = rng.standard_normal((N, K)) * 0.01
    w_nk[:, 0] = rng.standard_normal(N) * 50.0 + 50.0  # outlier K-index
    w = w_nk.T.astype(np.float32)  # [K, N], non-transposed MatMul weight
    model = _matmul_model(w, K, N)

    q = onnxsim.apply_quip_sharp_cpp(model)
    onnx.checker.check_model(q)

    naive_recon_nk = _naive_group_quant_nk(w_nk.astype(np.float64))
    naive_w = naive_recon_nk.T.astype(np.float32)
    naive_model = _matmul_model(naive_w, K, N)

    x = rng.standard_normal((4, K)).astype(np.float32)
    (true_y,) = _run(model, {"X": x})
    (quip_y,) = _run(q, {"X": x})
    (naive_y,) = _run(naive_model, {"X": x})

    quip_err = _rel_l2(true_y, quip_y)
    naive_err = _rel_l2(true_y, naive_y)
    assert quip_err < naive_err * 0.5


def test_cpp_gemm_with_bias():
    rng = np.random.default_rng(5)
    K, N = _GROUP_SIZE * 4, 8
    weight = rng.standard_normal((K, N)).astype(np.float32) * 0.5
    bias = rng.standard_normal((N,)).astype(np.float32) * 0.1
    model = _model(
        f"""
        g (float[batch,{K}] X) => (float[batch,{N}] Y)
        {{
          Y = Gemm(X, W, B)
        }}
        """,
        initializer=[_f32(weight, "W"), _f32(bias, "B")],
    )
    q = onnxsim.apply_quip_sharp_cpp(model)
    onnx.checker.check_model(q)

    x = rng.standard_normal((4, K)).astype(np.float32)
    (float_y,) = _run(model, {"X": x})
    (q_y,) = _run(q, {"X": x})
    assert np.all(np.isfinite(q_y))
    assert _rel_l2(float_y, q_y) < 0.5


def test_cpp_gemm_transb():
    rng = np.random.default_rng(8)
    K, N = _GROUP_SIZE * 2, 6
    weight = rng.standard_normal((N, K)).astype(np.float32) * 0.5
    model = _model(
        f"""
        g (float[batch,{K}] X) => (float[batch,{N}] Y)
        {{
          Y = Gemm<transB = 1>(X, W)
        }}
        """,
        initializer=[_f32(weight, "W")],
    )
    q = onnxsim.apply_quip_sharp_cpp(model)
    onnx.checker.check_model(q)
    new_w = _current_weight(q)
    assert new_w.shape == weight.shape


def test_cpp_noop_when_no_matmul_gemm_present():
    model = _model(
        """
        g (float[4,4] X) => (float[4,4] Y)
        {
          Y = Relu(X)
        }
        """
    )
    result = onnxsim.apply_quip_sharp_cpp(model)
    assert result.SerializeToString() == model.SerializeToString()


def test_cpp_skips_non_2d_weight():
    rng = np.random.default_rng(7)
    w = rng.standard_normal((2, 4, 4, 4)).astype(np.float32)
    model = _model(
        """
        g (float[1,2,8,8] X) => (float[1,2,5,5] Y)
        {
          Y = Conv(X, W)
        }
        """,
        [_f32(w, "W")],
    )
    result = onnxsim.apply_quip_sharp_cpp(model)
    assert result.SerializeToString() == model.SerializeToString()


def test_cpp_skips_non_group_divisible_k():
    # K not a multiple of 8 -- quip_sharp.py's own encoder skips this
    # layer entirely (no ragged-last-group handling), and this port
    # matches that exactly.
    rng = np.random.default_rng(9)
    K, N = _GROUP_SIZE + 3, 4
    w = rng.standard_normal((K, N)).astype(np.float32)
    model = _matmul_model(w, K, N)
    result = onnxsim.apply_quip_sharp_cpp(model)
    assert result.SerializeToString() == model.SerializeToString()
