"""Cross-checks `scripts/renesas/drp_ai_tvm_ops.py`'s scraped TVM v0.8
op-support data against the REAL, installed `tvm` package -- see
`scripts/renesas/tvm_v08_frontend_backend.py`'s module docstring for what
"real" means here (the open-source TVM ONNX frontend, still not DRP-AI
hardware acceleration or the DRP-AI Translator, which stay out of reach
without a Renesas account).

Skipped entirely if `tvm` isn't importable, matching
`tests/test_axelera_voyager_real_compiler.py`'s pattern for its own
optional real-compiler dependency. In this repo's CI, only
`.github/workflows/renesas-integration.yml`'s `real-tvm-v08-frontend` job
(which builds TVM v0.8 from source -- see that workflow and
`tvm_v08_frontend_backend.py` for why this can't just be `pip install`) has
`tvm` installed; everywhere else (including a plain local `pytest` run)
this file's tests report as skipped, not failed.

Written to run under the Python <=3.8 interpreter TVM v0.8 requires (see
`tvm_v08_frontend_backend.py`'s docstring) -- deliberately avoids newer
syntax (PEP 604 `X | Y` unions, PEP 585 builtin generics as runtime
annotations, etc.) that this specific test file needs to *parse* under.
"""

import os
import sys

import onnx
import pytest
from onnx import parser

_RENESAS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts", "renesas"
)
if _RENESAS_DIR not in sys.path:
    sys.path.insert(0, _RENESAS_DIR)

drp_ai_tvm_ops = pytest.importorskip("drp_ai_tvm_ops")
drp_ai_tvm_simulator = pytest.importorskip("drp_ai_tvm_simulator")
backend = pytest.importorskip("tvm_v08_frontend_backend")

if not backend.has_tvm():
    pytest.skip(
        "real tvm package not installed -- see "
        ".github/workflows/renesas-integration.yml's real-tvm-v08-frontend "
        "job for how CI builds it from source",
        allow_module_level=True,
    )


def _model(body, opset=13, ir_version=7):
    model = parser.parse_model(
        """
        <
          ir_version: %d,
          opset_import: ["": %d]
        >
        %s
        """
        % (ir_version, opset, body)
    )
    onnx.checker.check_model(model)
    return model


def test_scraped_convert_map_matches_real_installed_tvm():
    # The single strongest check in this file: not a graph-level behavior
    # test, but a direct diff between the scraped snapshot
    # (tvm_v08_onnx_frontend_op_support_data.py, committed) and the *live*
    # dict the actually-installed tvm package returns. Any mismatch means
    # the scrape is stale relative to whatever TVM build this job produced.
    #
    # This is also what caught drp_ai_tvm_ops.py's own "Constant is a
    # GraphProto.from_onnx() special case, not a _get_convert_map() entry"
    # claim being wrong: this exact assertion failed in CI with "Constant"
    # as an extra item on the real side, because it's an ordinary dict
    # entry -- see that module's docstring for the corrected account.
    assert drp_ai_tvm_ops.DRP_AI_TVM_IMPORTABLE_OPS == backend.real_convert_map_ops()


def test_real_tvm_imports_a_small_importable_op_graph():
    model = _model("""
        g (float[1,3,8,8] x) => (float[1,3,8,8] y)
        {
          r = Relu(x)
          y = Sigmoid(r)
        }
        """)
    ok, err = backend.try_import(model)
    assert ok, err


def test_real_tvm_rejects_unimportable_op_matching_predicted_message():
    model = _model(
        """
        g (float[1,4] x, float[4] scale, float[4] bias) => (float[1,4] y)
        { y = LayerNormalization(x, scale, bias) }
        """,
        opset=17,
    )
    predicted = drp_ai_tvm_simulator.unsupported_op_error_message(model)
    ok, err = backend.try_import(model)
    assert not ok
    assert predicted in err, (predicted, err)


def test_conv_bn_relu_fixture_before_and_after_simplify_both_import():
    # Generated by scripts/renesas/gen_simplify_fixtures.py in a separate,
    # Python->=3.11 CI job (onnxsim itself needs >=3.11, incompatible with
    # this job's <=3.8 TVM build -- see that script's docstring) and handed
    # across as a build artifact. Skips (not fails) outside that CI job, or
    # if the fixture-generation step didn't run -- this test's purpose is
    # confirming a real onnxsim.simplify() output round-trips through the
    # real TVM frontend, which needs those files to exist at all.
    fixture_dir = os.environ.get("RENESAS_SIMPLIFY_FIXTURE_DIR")
    if not fixture_dir:
        pytest.skip("RENESAS_SIMPLIFY_FIXTURE_DIR not set")
    before = onnx.load(os.path.join(fixture_dir, "conv_bn_relu_before.onnx"))
    after = onnx.load(os.path.join(fixture_dir, "conv_bn_relu_after.onnx"))

    ok, err = backend.try_import(before)
    assert ok, err
    ok, err = backend.try_import(after)
    assert ok, err

    after_ops = {n.op_type for n in after.graph.node}
    assert "BatchNormalization" not in after_ops, (
        "fixture should already have BatchNormalization folded into Conv "
        "by onnxsim -- regenerate via gen_simplify_fixtures.py"
    )
