#!/usr/bin/env python3
"""Emits a small multi-node ``.onnx`` fixture (Conv3D -> Relu) plus a
"ground truth" WebGPU kernel spec for it, generated via **tinygrad's own
generic ONNX importer** (``tinygrad.nn.onnx.OnnxRunner``) rather than any
onnxsim-specific per-op translation -- unlike
``onnxsim/webgpu_tinygrad_codegen.py``'s ``generate_conv_kernel`` (which
hand-builds a tinygrad ``Tensor`` graph one op at a time, and only covers
``Conv``/``Resize``), ``OnnxRunner`` parses *any* ONNX graph itself (it has
its own hand-rolled protobuf reader -- no dependency on the ``onnx`` Python
package at all) and drives tinygrad's op table generically, so this fixture
exercises a genuinely different, much broader code path: two chained ops,
one of which (``Relu``) onnxsim has no bespoke codegen for at all.

``pyodide_webgpu_onnxrunner_codegen.test.mjs`` regenerates this same spec
*live*, inside Pyodide, using ``OnnxRunner`` directly on the raw ``.onnx``
bytes (no JS-side shape/attribute reader needed at all this time -- see that
test's own docstring for why that's a further simplification over
``onnx_conv_node_reader.mjs``'s approach), and checks the two match exactly
before dispatching the live one against a real WebGPU device.

Regenerate (needs ``onnx``, ``numpy``, and ``tinygrad`` -- unlike
``make_webgpu_kernel_fixture.py``'s own fixture, this one's *reference spec*
itself is generated by tinygrad, not just checked against it, so tinygrad is
required here, not optional)::

    pip install onnx numpy 'tinygrad==0.14.0'
    python3 make_webgpu_onnxrunner_fixture.py
"""

import json
import os
import re

import numpy as np
import onnx
from onnx import numpy_helper, parser
from onnx.reference import ReferenceEvaluator

HERE = os.path.dirname(os.path.abspath(__file__))

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _flat(array: np.ndarray):
    return [float(v) for v in array.reshape(-1)]


def _base_buffer(t):
    from tinygrad.uop.ops import Ops

    for u in t.uop.toposort():
        if u.op is Ops.BUFFER:
            return u
    return None


def _encode_float(v: float):
    if v != v:
        return "NaN"
    if v == float("inf"):
        return "Infinity"
    if v == float("-inf"):
        return "-Infinity"
    return v


def _lower_tensor_program(named_tensors, output_name):
    """Same helper as ``onnxsim.webgpu_tinygrad_codegen._lower_tensor_program``
    (and the copy embedded in ``pyodide_webgpu_single_node_codegen.test.mjs``)
    -- duplicated here rather than imported, since this script deliberately
    avoids depending on onnxsim itself (see module docstring) and the JS test
    this fixture feeds needs its own copy anyway (it runs inside Pyodide, not
    against a real onnxsim install).
    """
    from tinygrad.codegen import to_program
    from tinygrad.helpers import Target
    from tinygrad.renderer.wgsl import WGSLRenderer
    from tinygrad.uop.ops import Ops

    output = named_tensors[output_name]
    linear = output.schedule_linear()
    kernel_calls = [
        u for u in linear.toposort() if u.op is Ops.CALL and u.src[0].op is Ops.SINK
    ]
    if not kernel_calls:
        raise RuntimeError(
            "tinygrad scheduled no compute kernel -- the graph may have constant-folded away"
        )

    uop_to_name = {}
    for name, t in named_tensors.items():
        buf = _base_buffer(t)
        if buf is None:
            raise RuntimeError(
                f"tensor {name!r} has no underlying BUFFER after scheduling"
            )
        uop_to_name[buf] = name

    renderer = WGSLRenderer(Target())
    steps = []
    intermediate_names = {}
    intermediate_bytes = {}
    next_intermediate = [0]

    def _name_for(buf_uop):
        name = uop_to_name.get(buf_uop)
        if name is not None:
            return "tensor", name
        name = intermediate_names.get(buf_uop)
        if name is None:
            name = f"_intermediate_{next_intermediate[0]}"
            next_intermediate[0] += 1
            intermediate_names[buf_uop] = name
            intermediate_bytes[name] = buf_uop.size()[0] * buf_uop.dtype.itemsize
        return "intermediate", name

    for call in kernel_calls:
        ast = call.src[0]
        buffer_uops = list(call.src[1:])
        prg = to_program(ast, renderer)
        info = prg.arg
        source_uop = next(s for s in prg.src if s.op is Ops.SOURCE)
        wgsl = source_uop.arg
        entry_point = _ANSI_RE.sub("", info.function_name)

        bindings = [
            {
                "group": 0,
                "binding": 0,
                "access": "uniform",
                "constant": [_encode_float(float("inf"))],
            }
        ]
        for slot, buf_uop in enumerate(buffer_uops):
            kind, name = _name_for(buf_uop)
            if kind == "tensor":
                bindings.append(
                    {
                        "group": 0,
                        "binding": slot + 1,
                        "access": "read_write",
                        "tensor": name,
                    }
                )
            else:
                bindings.append(
                    {
                        "group": 0,
                        "binding": slot + 1,
                        "access": "read_write",
                        "intermediate": name,
                    }
                )

        padded_size = [int(x) for x in info.global_size] + [1, 1, 1]
        steps.append(
            {
                "wgsl": wgsl,
                "entry_point": entry_point,
                "dispatch": padded_size[:3],
                "bindings": bindings,
            }
        )

    return {"steps": steps, "intermediates": intermediate_bytes}


def _generate_ground_truth_spec(model_path, input_name, input_shape, output_name):
    """Runs the model through tinygrad's own generic ``OnnxRunner`` -- not
    any onnxsim per-op translation -- tagged for the ``WEBGPU`` device, and
    lowers the result to a WGSL kernel spec. Uses random dummy data (a
    different seed than the fixture's own real values -- see this function's
    caller): kernel generation only depends on shapes/attributes, never on
    tensor values (see ``onnxsim/webgpu_tinygrad_codegen.py``'s own module
    docstring), so generating the "ground truth" spec from different
    concrete values than ``pyodide_webgpu_onnxrunner_codegen.test.mjs``'s own
    live run uses, and still asserting an exact match, is the whole point --
    it proves the match isn't a coincidence of using identical inputs.

    Constructing every tensor -- including initializers ``OnnxPBParser``
    itself parses on tinygrad's *default* device -- directly on ``WEBGPU``
    via ``Context(DEV="WEBGPU")`` (rather than parsing on the default device
    and calling ``.to("WEBGPU")`` afterward) matters here: a same-thread
    ``.to()`` device transfer, once scheduled, materializes into a *new*
    buffer distinct from the one captured before scheduling, so matching an
    initializer's own pre-transfer buffer identity against the buffer the
    compiled kernel actually reads silently fails (found the hard way,
    comparing buffer object identity directly) -- constructing on ``WEBGPU``
    from the start avoids the transfer, and therefore the mismatch, entirely.

    Even the ``import`` of ``tinygrad.nn.onnx`` must happen inside the
    ``Context`` block, not just the tensors this function itself builds:
    that module evaluates a stray ``Tensor(0)`` default argument (for
    ``ConvInteger``) at *module import* time, which resolves tinygrad's
    device default the same way any other tensor construction would --
    found the hard way again, in a real environment with no other usable
    tinygrad device at all (Pyodide, see this fixture's own JS-side test),
    where that bare import fails outright with "no usable devices" unless
    it, too, runs inside ``Context(DEV="WEBGPU")``.
    """
    import random

    from tinygrad.helpers import Context

    random.seed(1)

    def _rand(*shape):
        if len(shape) == 1:
            return [random.gauss(0, 1) for _ in range(shape[0])]
        return [_rand(*shape[1:]) for _ in range(shape[0])]

    with Context(DEV="WEBGPU"):
        from tinygrad import Tensor
        from tinygrad.nn.onnx import OnnxRunner

        run = OnnxRunner(model_path)
        initializer_names = [k for k in run.graph_values if k != ""]
        outputs = run({input_name: Tensor(_rand(*input_shape))})
        named = {
            name: run.graph_values[name] for name in [*initializer_names, input_name]
        }
        named[output_name] = outputs[output_name]
        return _lower_tensor_program(named, output_name)


def main():
    x_shape, w_shape = (1, 2, 4, 4, 4), (2, 2, 3, 3, 3)
    rng = np.random.default_rng(0)
    x = rng.standard_normal(x_shape).astype(np.float32)
    w = rng.standard_normal(w_shape).astype(np.float32)

    model = parser.parse_model(
        f"""
        <ir_version: 10, opset_import: ["": 17]>
        g (float{list(x_shape)} x) => (float[?] z)
        {{
          y = Conv<kernel_shape = [3, 3, 3]>(x, w)
          z = Relu(y)
        }}
        """
    )
    model.graph.initializer.append(numpy_helper.from_array(w, "w"))
    model.graph.node[0].name = "conv3d_node"
    model.graph.node[1].name = "relu_node"
    onnx.checker.check_model(model)

    (z_ref,) = ReferenceEvaluator(model).run(None, {"x": x})

    model_path = os.path.join(HERE, "webgpu_onnxrunner_conv_relu.onnx")
    onnx.save(model, model_path)

    ground_truth_spec = _generate_ground_truth_spec(model_path, "x", x_shape, "z")

    manifest = {
        "file": "webgpu_onnxrunner_conv_relu.onnx",
        "inputName": "x",
        "outputName": "z",
        "inputs": {
            "x": {"shape": list(x_shape), "data": _flat(x)},
            "w": {"shape": list(w_shape), "data": _flat(w)},
        },
        "expectedOutput": {"shape": list(z_ref.shape), "data": _flat(z_ref)},
        "groundTruthSpec": ground_truth_spec,
    }
    manifest_path = os.path.join(HERE, "webgpu_onnxrunner_fixture.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")

    print("wrote", model_path)
    print("wrote", manifest_path)
    print(f"ground truth spec has {len(ground_truth_spec['steps'])} kernel step(s)")


if __name__ == "__main__":
    main()
