"""ONNX -> TFLite Micro C array, for baking a model into an ESP32-S3 firmware
image (see ../firmware/README.md for what happens to the header this emits).

Two independent pieces, split because only the second is dependency-free:

- ``convert_to_tflite()`` shells out to ``onnx2tf`` (a separate pip package;
  not a dependency of onnxsim itself -- see the top-level CLAUDE.md's note
  that onnxsim's own pipeline never needs a TFLite/nncase toolchain). Run the
  onnxsim model converter (../../convertmodel or the Python API) first to
  simplify/quantize -- this script only does the ONNX -> TFLite step.
- ``emit_c_header()`` is pure Python (stdlib only): it turns arbitrary bytes
  into a C header, the same "flatbuffer as a byte array linked into the
  binary" pattern every TFLite Micro example uses. It has no onnx2tf/
  TensorFlow dependency, so it's unit-tested directly (see ../tests/).

Status: emit_c_header() is exercised by ../tests/test_onnx_to_tflite_micro.py.
convert_to_tflite() (the onnx2tf subprocess call) is not run in CI -- onnx2tf
pulls in TensorFlow, which this repo's own CI doesn't install anywhere else --
so treat that half as reviewed, not verified end-to-end.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# TFLite Micro's own convention (e.g. the Arduino/ESP-IDF example projects):
# aligning the flatbuffer avoids an unaligned-read fault when the interpreter
# reads multi-byte fields straight out of the array.
_ALIGNMENT = 16


def convert_to_tflite(onnx_path: Path, out_dir: Path, *, quant_int8: bool = True) -> Path:
    """Run onnx2tf, returning the path to the produced .tflite file.

    onnx2tf writes several outputs (float32, float16, and -- with
    ``-oiqt`` -- an INT8 quantized model using its own built-in calibration
    data) into ``out_dir``; TFLite Micro on an ESP32-S3 wants the INT8 one
    for both size and the CPU's lack of a float unit worth relying on.
    """
    if shutil.which("onnx2tf") is None:
        raise RuntimeError(
            "onnx2tf not found on PATH -- pip install onnx2tf (and its own "
            "TensorFlow dependency) first; this script doesn't vendor it."
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = ["onnx2tf", "-i", str(onnx_path), "-o", str(out_dir)]
    if quant_int8:
        cmd.append("-oiqt")
    subprocess.run(cmd, check=True)

    suffix = "_integer_quant.tflite" if quant_int8 else "_float32.tflite"
    matches = sorted(out_dir.glob(f"*{suffix}"))
    if not matches:
        raise RuntimeError(f"onnx2tf did not produce a *{suffix} file in {out_dir}")
    return matches[0]


def emit_c_header(data: bytes, var_name: str) -> str:
    """Render `data` as a C header: an aligned byte array plus its length.

    Matches the shape every TFLite Micro example expects
    (``tflite::GetModel(g_model)`` + a separately-passed length), so the
    generated header can be dropped into an example sketch/project as-is.
    """
    if not var_name.isidentifier():
        raise ValueError(f"not a valid C identifier: {var_name!r}")

    lines = [f"// Generated by {Path(__file__).name} -- do not edit by hand.", ""]
    lines.append(f"alignas({_ALIGNMENT}) const unsigned char {var_name}[] = {{")
    for offset in range(0, len(data), 12):
        row = data[offset : offset + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in row) + ",")
    lines.append("};")
    lines.append(f"const unsigned int {var_name}_len = {len(data)};")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("onnx_model", type=Path, help="simplified/quantized .onnx file")
    parser.add_argument("out_path", type=Path,
                         help="where to write the result -- a .tflite extension writes the plain "
                              "converted model (for the runtime firmware's flash-partition load path, "
                              "see ../firmware/runtime/README.md); anything else writes a C header")
    parser.add_argument("--var-name", default="g_model", help="C array name (default: g_model, .h output only)")
    parser.add_argument("--tflite-dir", type=Path, default=None,
                         help="where onnx2tf writes its outputs (default: alongside out_path)")
    parser.add_argument("--no-int8", action="store_true", help="keep float32 instead of quantizing")
    args = parser.parse_args(argv)

    tflite_dir = args.tflite_dir or args.out_path.parent / "tflite_out"
    tflite_path = convert_to_tflite(args.onnx_model, tflite_dir, quant_int8=not args.no_int8)

    if args.out_path.suffix == ".tflite":
        args.out_path.write_bytes(tflite_path.read_bytes())
    else:
        header = emit_c_header(tflite_path.read_bytes(), args.var_name)
        args.out_path.write_text(header)
    print(f"wrote {args.out_path} ({tflite_path.stat().st_size} bytes from {tflite_path.name})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
