/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * cv::Mat <-> flat-buffer glue for a model generated by
 * onnxsim.generate_xnnpack_c / onnxsim/xnnpack_codegen.h.
 *
 * This header is a template, not a library: copy it into your own C++
 * project alongside the generated .c file (rename the .c file's include
 * guard-free `#include <xnnpack.h>` etc. stay as-is; this header only needs
 * a `float*`/shape pair on one side, so it does not need to see the
 * generated file's own symbols at all). It is not compiled by onnxsim's own
 * build -- onnxsim otherwise has no OpenCV dependency, and this header would
 * force one -- so nothing here is exercised by onnxsim's own test suite;
 * treat it as documented, reviewed sample code rather than a tested library
 * function.
 *
 * Why this exists: onnxsim/xnnpack_codegen.h emits every 4-D (image-shaped)
 * tensor as NHWC (batch, height, width, channels) -- not ONNX's own NCHW --
 * specifically because that is XNNPACK's native convolution layout *and*
 * the natural in-memory layout of an interleaved OpenCV image: a
 * `CV_32FC3`/`CV_8UC3` cv::Mat already stores each pixel's channels
 * contiguously, row-major, top-to-bottom -- i.e. exactly NHWC (with N=1).
 * So feeding a generated model's first input from a cv::Mat needs no
 * transpose at all, only (a) a dtype conversion if the Mat isn't already
 * float32, and (b) a copy if the Mat is not contiguous (see below) -- never
 * a data *reorder*.
 *
 * ---- Why a non-contiguous cv::Mat needs an actual copy, not just a cast ----
 *
 * cv::Mat's `data` pointer is not always a tightly-packed NHWC buffer: each
 * row can carry trailing padding, and a Mat can be a *view* into a larger
 * one (an ROI/sub-Mat via `Mat::operator()(Rect)`, or a strided channel
 * split) -- in both cases `Mat::step` (the real, possibly-padded byte
 * stride between rows) differs from `cols * elemSize()` (the tightly-packed
 * stride a flat NHWC buffer needs), and `Mat::isContinuous()` is false. That
 * is a real, physical difference in memory layout, not a labeling one --
 * the padding bytes genuinely sit between rows in memory -- so treating
 * such a Mat's `data` pointer as one contiguous buffer would silently read
 * (or write) garbage past each row's real pixels. ToNhwcFloat32 below
 * handles this the same way a Transpose op would: only a bare pointer cast
 * when the layout already matches (isContinuous() and already float32,
 * O(1), no copy), and a real per-row copy otherwise (O(rows*cols*channels),
 * unavoidable -- this is the same "materializing copy" data movement
 * described in onnxsim/xnnpack_codegen.h's module comment, just for a
 * *row*-strided source instead of a transposed one).
 */
#ifndef ONNXSIM_XNNPACK_CV_MAT_HPP_
#define ONNXSIM_XNNPACK_CV_MAT_HPP_

#include <cstring>
#include <opencv2/core.hpp>
#include <stdexcept>
#include <vector>

namespace onnxsim {
namespace xnnpack_cv_mat {

// Returns `mat`'s pixels as a tightly-packed, row-major NHWC float32 buffer
// (N=1) ready to hand to a generated model's `<prefix>_run` as one input --
// `out` is resized to exactly `rows*cols*channels` floats. Reuses `mat`'s
// own buffer with zero copies when it is already continuous float32 data
// (the common case for a freshly-allocated, non-ROI Mat); otherwise copies
// once, converting dtype and/or removing row padding as needed.
//
// Throws std::invalid_argument if `mat` is empty. Any depth cv::Mat
// supports converts via cv::Mat::convertTo (integer pixel types are
// rescaled 0..1 -- see OpenCV's own convertTo(..., CV_32F, 1.0/255) idiom;
// pass `scale`/`shift` through if a model expects a different input range,
// e.g. `scale=1.0` to keep raw 0..255 values instead).
inline void ToNhwcFloat32(const cv::Mat& mat, std::vector<float>& out,
                          double scale = 1.0 / 255.0, double shift = 0.0) {
  if (mat.empty()) {
    throw std::invalid_argument("ToNhwcFloat32: mat is empty");
  }
  const bool needs_convert =
      mat.depth() != CV_32F || scale != 1.0 || shift != 0.0;
  const cv::Mat* src = &mat;
  cv::Mat converted;
  if (needs_convert) {
    mat.convertTo(converted, CV_MAKETYPE(CV_32F, mat.channels()), scale, shift);
    src = &converted;
  }
  const size_t n = static_cast<size_t>(src->rows) * src->cols * src->channels();
  out.resize(n);
  if (src->isContinuous()) {
    std::memcpy(out.data(), src->ptr<float>(0), n * sizeof(float));
    return;
  }
  // Not continuous (padded rows or an ROI view): copy row by row, each of
  // which *is* contiguous on its own (cv::Mat never pads mid-row).
  const size_t row_floats = static_cast<size_t>(src->cols) * src->channels();
  for (int r = 0; r < src->rows; ++r) {
    std::memcpy(out.data() + static_cast<size_t>(r) * row_floats,
                src->ptr<float>(r), row_floats * sizeof(float));
  }
}

// The inverse of ToNhwcFloat32 for a rank-4 (image-shaped) *output* --
// wraps `data` (must stay alive at least as long as the returned cv::Mat,
// which does not copy it) as an `height x width x channels` float32 Mat.
// For a rank-2 classifier-head output (e.g. after GlobalAveragePool ->
// Gemm, which this generator never re-inflates to 4-D -- see
// xnnpack_codegen.h), just read `data` directly as a plain float array
// instead; there is no image structure left to wrap.
inline cv::Mat WrapNhwcFloat32(float* data, int height, int width,
                               int channels) {
  return cv::Mat(height, width, CV_MAKETYPE(CV_32F, channels), data);
}

}  // namespace xnnpack_cv_mat
}  // namespace onnxsim

#endif  // ONNXSIM_XNNPACK_CV_MAT_HPP_
