// Cross-checks k210_isp.mjs's framing (crc32, buildPacket, slipEncode)
// against vectors.json, which was generated by literally re-implementing
// the same three functions in Python next to kflash.py's own source
// (see the generating script's comments in the PR/commit that added this --
// the point is these numbers came from running code, not from re-deriving
// the math by hand a second time in JS).
//
// This is the one piece of k210_isp.mjs that's actually verified against
// something authoritative; everything past the framing layer (the actual
// serial I/O, timing, retries) still needs a real board -- see
// ../web/k210_isp.mjs's own top-of-file status note.
//
// Run: node tests/test_protocol.mjs

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  crc32,
  buildPacket,
  slipEncode,
  GREETING_FRAME,
  FLASH_GREETING_FRAME,
  FLASH_ERASE_FRAME,
  RESET_SCHEMES,
} from "../web/k210_isp.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(readFileSync(path.join(here, "vectors.json"), "utf8"));

const hex = (bytes) => Buffer.from(bytes).toString("hex");
const fromHex = (h) => Uint8Array.from(Buffer.from(h, "hex"));

function test(name, fn) {
  try {
    fn();
    console.log(`ok - ${name}`);
  } catch (e) {
    console.error(`FAIL - ${name}`);
    console.error(e);
    process.exitCode = 1;
  }
}

test("crc32 matches known test vectors", () => {
  assert.equal(crc32(new Uint8Array(0)), vectors.crc32_empty);
  assert.equal(crc32(new TextEncoder().encode("123456789")), vectors.crc32_123456789);
  assert.equal(
    crc32(new TextEncoder().encode("The quick brown fox jumps over the lazy dog")),
    vectors.crc32_quickfox,
  );
});

test("buildPacket(0xc5, boot body) matches kflash.py's boot() bytes", () => {
  // struct.pack('II', 0x80000000, 0) -- address, then a reserved u32 of 0.
  const body = new Uint8Array(8);
  new DataView(body.buffer).setUint32(0, 0x80000000, true);
  const packet = buildPacket(0xc5, body);
  assert.equal(hex(packet), vectors.boot_packet_hex);
  assert.equal(hex(slipEncode(packet)), vectors.boot_packet_slip_hex);
});

test("buildPacket(0xc3, mem-write body) matches kflash.py's flash_dataframe() bytes", () => {
  const addr = new Uint8Array(4);
  new DataView(addr.buffer).setUint32(0, 0x80000000, true);
  const len = new Uint8Array(4);
  new DataView(len.buffer).setUint32(0, 4, true);
  const chunk = new Uint8Array([1, 2, 3, 4]);
  const body = new Uint8Array([...addr, ...len, ...chunk]);
  const packet = buildPacket(0xc3, body);
  assert.equal(hex(packet), vectors.memwrite_packet_hex);
  assert.equal(hex(slipEncode(packet)), vectors.memwrite_packet_slip_hex);
});

test("slipEncode escapes 0xc0 and 0xdb bytes inside the body", () => {
  const packet = fromHex(vectors.tricky_packet_hex);
  assert.equal(hex(slipEncode(packet)), vectors.tricky_packet_slip_hex);
});

test("GREETING_FRAME matches kflash.py's literal bytes exactly", () => {
  assert.equal(hex(GREETING_FRAME), vectors.literal_greeting_hex);
});

test("FLASH_GREETING_FRAME / FLASH_ERASE_FRAME follow the same literal shape (op + 12 zero bytes)", () => {
  assert.equal(hex(FLASH_GREETING_FRAME), "c0d2000000000000000000000000c0");
  assert.equal(hex(FLASH_ERASE_FRAME), "c0d3000000000000000000000000c0");
});

test("greeting/flash_greeting/flash_erase are literal frames, NOT buildPacket output", () => {
  // This is the bug this test suite exists to catch: kflash.py's greeting()
  // sends a hardcoded 15-byte literal that buildPacket(0xc2, empty) does
  // NOT reproduce (8 header bytes vs. the literal's 13-byte body) --
  // k210_isp.mjs must hardcode these three frames rather than build them.
  const built = slipEncode(buildPacket(0xc2, new Uint8Array(0)));
  assert.notEqual(hex(built), vectors.literal_greeting_hex,
    "buildPacket must NOT match the literal greeting frame -- if it now does, kflash.py's format changed and k210_isp.mjs's literals need re-checking, not deleting");
});

test("RESET_SCHEMES match kflash.py's reset_to_isp_*()/reset_to_boot_*() sequences exactly", () => {
  // [dtr, rts] per step, re-checked against kflash.py's source line-by-line
  // (not from memory) at the time these were added.
  assert.deepEqual(RESET_SCHEMES.dan, {
    isp: [[false, false], [false, true], [true, false]],
    boot: [[false, false], [false, true], [false, false]],
  });
  assert.deepEqual(RESET_SCHEMES.kd233, {
    isp: [[false, false], [true, false], [false, true]],
    boot: [[false, false], [true, false], [false, false]],
  });
  assert.deepEqual(RESET_SCHEMES.goD, {
    isp: [[true, true], [true, false], [true, false]],
    boot: [[false, false], [true, false], [true, true]],
  });
});

test("isp_stub.bin is intact (size + crc32 against the value computed when it was extracted)", () => {
  const stub = readFileSync(path.join(here, "..", "web", "isp_stub.bin"));
  assert.equal(stub.length, 66304);
  assert.equal(crc32(stub), 0x6e42076b);
});

if (process.exitCode) {
  console.error("\nSome tests failed.");
} else {
  console.log("\nAll protocol tests passed.");
}
